export const ProjectsData = [
  {
    id: 1,
    name: 'Obstacle Avoiding Robot',
    image: '/images/obstacle-avoider.jpg',
    price: 2500,
    rating: 4.5,
    description:
      "This robot autonomously navigates environments by detecting obstacles using ultrasonic sensors. It's an ideal project for beginners looking to understand basic motor control, distance sensing, and logic-based navigation. The robot stops, turns, and re-routes when an object is detected in its path.",
    time: 2,
    totalDelivered: 15,
    components: [
      'Arduino Uno',
      'Ultrasonic Sensor (HC-SR04)',
      'L298N Motor Driver',
      'DC Motors x2',
      'Caster Wheel',
      'Robot Chassis',
      '9V Battery & Clip',
      'Jumper Wires',
    ],
  },
  {
    id: 2,
    name: 'Line Following Robot',
    image: '/images/line-follower.webp',
    price: 2000,
    rating: 4.2,
    description:
      "A classic robotics project where the robot uses infrared sensors to follow a black line on a white surface. It's excellent for learning PID control, sensor calibration, and real-world feedback-based control. This robot can be enhanced with speed control and path branching logic.",
    time: 1,
    totalDelivered: 22,
    components: [
      'Arduino Uno',
      'IR Sensor Module x2',
      'L298N Motor Driver',
      'DC Motors x2',
      'Robot Chassis',
      'Battery Pack (9V or 12V)',
      'Jumper Wires',
      'Wheels & Caster',
    ],
  },
  {
    id: 3,
    name: 'Voice Controlled Robot',
    image: '/images/voice-control.jpg',
    price: 3200,
    rating: 4.7,
    description:
      'This robot listens to and interprets voice commands using a speech recognition module. It moves in various directions based on your voice inputs. Great for understanding serial communication, voice-to-command logic, and real-time robot control through human interaction.',
    time: 3,
    totalDelivered: 8,
    components: [
      'Arduino Uno',
      'Speech Recognition Module (e.g., Elechouse V3)',
      'L298N Motor Driver',
      'DC Motors x2',
      'Robot Chassis',
      'Battery',
      'Microphone',
      'Wheels, Wires, Caster',
    ],
  },
  {
    id: 4,
    name: 'Robotic Arm with Joystick',
    image: '/images/robotic-arm.jpg',
    price: 4500,
    rating: 4.8,
    description:
      'A multi-joint robotic arm controlled by a joystick, capable of lifting and moving small objects. It helps learners dive deep into servo motor control, axis coordination, inverse kinematics, and user-input-based movement precision. A perfect project for intermediate-level robotics.',
    time: 4,
    totalDelivered: 10,
    components: [
      'Arduino Uno',
      'Servo Motors x4',
      'Joystick Module',
      'Robotic Arm Frame',
      'Breadboard',
      'Power Supply (5V)',
      'Jumper Wires',
      'Screws/Nuts for Assembly',
    ],
  },
  {
    id: 5,
    name: 'Smart Wheelchair with Sensors',
    image: '/images/smart-wheelchair.jpg',
    price: 5500,
    rating: 5.0,
    description:
      'An advanced project that integrates patient-centric technology into mobility solutions. The wheelchair features object detection via ultrasonic sensors, health monitoring (temperature, heartbeat), and intuitive control through joystick or hand tilt using a gyro sensor. It prioritizes safety and ease of use.',
    time: 5,
    totalDelivered: 5,
    components: [
      'Arduino Uno',
      'Ultrasonic Sensors x2',
      'LM35 Temperature Sensor',
      'Heartbeat Sensor',
      'Gyroscope (MPU6050)',
      'Joystick Module',
      'L298N Motor Driver',
      'Wheelchair Frame with Motors',
      '12V Battery',
    ],
  },
];
